name: Publish

env:
  module_id: transitions

on:
  workflow_dispatch:
    inputs:
      release_ver:
        description: "Version to release (v will be added to the tag)"
        required: true
      release_msg:
        description: "Message for release"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        name: Checkout
        with:
          submodules: true
          lfs: true

      - name: Setup QPM
        uses: Fernthedev/qpm-action@v1
        with:
          workflow_token: ${{ secrets.GITHUB_TOKEN }}
          restore: true
          resolve_ndk: true
          cache: true

      - name: Build & Create QMOD
        run: |
          cd ${GITHUB_WORKSPACE}
          qpm qmod zip

      - name: Get Output Names
        id: names
        run: |
          pattern="*.qmod"
          files=( $pattern )
          echo QMOD="${files[0]}" >> $GITHUB_OUTPUT
          cd build
          pattern="lib${module_id}*.so"
          files=( $pattern )
          echo LIB="${files[0]}" >> $GITHUB_OUTPUT
          cd debug
          mv ${files[0]} debug_${files[0]}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.inputs.release_msg }}
          tag_name: "v${{ github.event.inputs.release_ver }}"
          files: |
            build/${{ steps.names.outputs.LIB }}
            build/debug/debug_${{ steps.names.outputs.LIB }}
            ${{ steps.names.outputs.QMOD }}
